//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CommentCellId`.
    static let commentCellId: Rswift.ReuseIdentifier<CommitCommentTableViewCell> = Rswift.ReuseIdentifier(identifier: "CommentCellId")
    /// Reuse identifier `EventMainCellId`.
    static let eventMainCellId: Rswift.ReuseIdentifier<EventMainTableViewCell> = Rswift.ReuseIdentifier(identifier: "EventMainCellId")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 1 view controllers.
  struct segue {
    /// This struct is generated for `GHEventsFeedTableViewController`, and contains static references to 2 segues.
    struct ghEventsFeedTableViewController {
      /// Segue identifier `EventDetailsSegue`.
      static let eventDetailsSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, GHEventsFeedTableViewController, EventDetailsTableViewController> = Rswift.StoryboardSegueIdentifier(identifier: "EventDetailsSegue")
      /// Segue identifier `userProfileSegue`.
      static let userProfileSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, GHEventsFeedTableViewController, UserProfileViewController> = Rswift.StoryboardSegueIdentifier(identifier: "userProfileSegue")
      
      /// Optionally returns a typed version of segue `EventDetailsSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func eventDetailsSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, GHEventsFeedTableViewController, EventDetailsTableViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.ghEventsFeedTableViewController.eventDetailsSegue, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `userProfileSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func userProfileSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, GHEventsFeedTableViewController, UserProfileViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.ghEventsFeedTableViewController.userProfileSegue, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      /// Value: Filter Events
      static let filterEvents = Rswift.StringResource(key: "Filter Events", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Oups! the information about this event has not been parsed yet😅
      static let noInformationAvailable = Rswift.StringResource(key: "No Information Available", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Filter Events
      static func filterEvents(_: Void = ()) -> String {
        return NSLocalizedString("Filter Events", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Oups! the information about this event has not been parsed yet😅
      static func noInformationAvailable(_: Void = ()) -> String {
        return NSLocalizedString("No Information Available", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
